version: 2.1
jobs:
  build:
    working_directory: ~/redux-async
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          keys:
            yarn-cache-{{ checksum "yarn.lock" }}
            - yarn-cache-
      - run: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run:
          name: Run Tests
          command: yarn test